### ISSUE TITLE
How Do I Find My API Key

### ISSUE THREAD

**Issue by werner33** [jamesrweb/codewars-kata-exporter#7]
HI there James, 

Can you help me know how to locate my API key from Codewars? I remember it being in the account settings but I don't see it there now. 

Thanks!

**Comment by jamesrweb** [comment]
Actually it seems that they have removed the _need_ for an API key as you can see in [the developer documentation](https://dev.codewars.com/). I will update the repo accordingly to reflect this or if you feel up to it, I would appreciate a quick PR if you could?

Either way, when the repo is updated I will re-publish the package.

**Comment by werner33** [comment]
Kind of. Some of the end points are fully exposed but there are some
undocumented endpoints for submitting solutions from a separate client.

It seems like in this case, it is now hard or impossible to use those end
points since I can't find my API key.

As an example: https://github.com/jacerhea/Codewars.API/blob/f7bd76b57feca232a5f5a36d8aa412f9580f48a3/src/Codewars.API/CodewarsClient.cs#L100

This is an undocumented endpoint from someone else's repo for submitting a solution, but it requires a users personal api key in the headers.

**Comment by jamesrweb** [comment]
If it is possible but not documented, that seems more like a major bug than a feature if that is the case. As seen in https://github.com/codewars/codewars.com/issues/2305 and https://github.com/codewars/codewars.com/issues/2414 for example, the API is very limited and always has been since I have used it years ago initially, but they are working on changing this!

This package could introduce that behaviour and more for these "hidden" endpoints though if you wanted to try implementing it and submitting a PR, it shouldn't be so hard since the implementation is easily extended as is.

If you want to get your API key, you could try reaching out to @kazk on the https://github.com/codewars/codewars.com repo, he is usually very helpful with this kind of thing!

**Comment by werner33** [comment]
Thanks, I just reached out to him on the Discord support channel. I'll see if he responds there. 

Sorry for gumming up your issues tab. 

Check out an app I've created at www.CodeTrack.dev if you would like. I can tell you like Codewars and so you'll probably get a kick out of it. It incorporates Codewars webhooks to good effect. 

Thanks for your help!

**Comment by jamesrweb** [comment]
Anytime @werner33, thanks for reaching out, I am glad to know about these recent changes also!

I will check it out for sure, thanks for the share!

All the best to you.
